const doB = "15-08-2001"; // constant values can not be changed.
let currentCity = "Patna"; // can be changed.
var currentState = "Bihar"; // can be changed.
currentDistrict = "Patna"; // variables can also be declared like this.
console.table([doB, currentCity, currentState, currentDistrict]);

/**
 * Always use let keyword because it resolves the issue of scope generated by var; 
 * 
 * Test this:
 */

let a = 4;
var b = 5;

for(let i=0; i<2; i++)
    {
        let a = 5; // not changed
        var b = 6;
    }

    console.table([a,b]);

    